"""
Client Endpoints Module

This module provides CRUD endpoints for managing client entities. Clients are
shared resources that all authenticated users can view, but only administrators
can create, update, or delete.
"""
from typing import List
from fastapi import APIRouter, Depends, HTTPException
from sqlmodel import Session, select
from app.db.session import get_db
from app.models.client import Client
from app.models.user import User
from app.api import deps

router = APIRouter()


@router.get("", response_model=List[Client])
def list_clients(
    skip: int = 0,
    limit: int = 100,
    db: Session = Depends(get_db),
    current_user: User = Depends(deps.get_current_active_user),
):
    """
    Retrieve a paginated list of clients.
    
    All authenticated users can view all clients. Clients are treated as shared
    resources in the system.
    
    Args:
        skip: Number of records to skip (for pagination)
        limit: Maximum number of records to return
        db: Database session
        current_user: Currently authenticated user
    
    Returns:
        List[Client]: List of client objects
    """
    # All users can see all clients (shared resource model)
    statement = select(Client).offset(skip).limit(limit)
    
    clients = db.exec(statement).all()
    return clients


@router.get("/{client_id}", response_model=Client)
def read_client(
    client_id: str,
    db: Session = Depends(get_db),
    current_user: User = Depends(deps.get_current_active_user),
):
    """
    Get a specific client by ID.
    
    All authenticated users can view any client.
    
    Args:
        client_id: UUID of the client to retrieve
        db: Database session
        current_user: Currently authenticated user
    
    Returns:
        Client: The requested client object
    
    Raises:
        HTTPException 404: If the client doesn't exist
    """
    client = db.get(Client, client_id)
    if not client:
        raise HTTPException(status_code=404, detail="Client not found")
    
    # Clients are accessible to all authenticated users
    return client


@router.post("", response_model=Client)
def create_client(
    client: Client,
    db: Session = Depends(get_db),
    current_user: User = Depends(deps.get_current_active_user),
):
    """
    Create a new client.
    
    Available to all authenticated users. The client ID is automatically
    generated as a UUID.
    
    Args:
        client: Client data to create
        db: Database session
        current_user: Currently authenticated user
    
    Returns:
        Client: The newly created client object
    """
    # Create client (UUID is auto-generated by the model)
    db.add(client)
    db.commit()
    db.refresh(client)
    return client


@router.patch("/{client_id}", response_model=Client)
def update_client(
    client_id: str,
    client_update: dict,
    db: Session = Depends(get_db),
    current_user: User = Depends(deps.get_current_active_user),
):
    """
    Update an existing client.
    
    Only administrators can update clients.
    
    Args:
        client_id: UUID of the client to update
        client_update: Dictionary of fields to update
        db: Database session
        current_user: Currently authenticated user
    
    Returns:
        Client: The updated client object
    
    Raises:
        HTTPException 404: If the client doesn't exist
        HTTPException 403: If the user is not an administrator
    """
    client = db.get(Client, client_id)
    if not client:
        raise HTTPException(status_code=404, detail="Client not found")
    
    # Only admins can update clients
    if "super_admin" not in current_user.roles and "admin" not in current_user.roles:
        raise HTTPException(status_code=403, detail="Not authorized")
    
    # Apply updates to the client
    for key, value in client_update.items():
        setattr(client, key, value)
    
    db.add(client)
    db.commit()
    db.refresh(client)
    return client


@router.delete("/{client_id}")
def delete_client(
    client_id: str,
    db: Session = Depends(get_db),
    current_user: User = Depends(deps.get_current_active_user),
):
    """
    Delete a client.
    
    Only administrators can delete clients.
    
    Args:
        client_id: UUID of the client to delete
        db: Database session
        current_user: Currently authenticated user
    
    Returns:
        dict: Success message
    
    Raises:
        HTTPException 404: If the client doesn't exist
        HTTPException 403: If the user is not an administrator
    """
    client = db.get(Client, client_id)
    if not client:
        raise HTTPException(status_code=404, detail="Client not found")
    
    # Only admins can delete clients
    if "super_admin" not in current_user.roles and "admin" not in current_user.roles:
        raise HTTPException(status_code=403, detail="Not authorized")
    
    db.delete(client)
    db.commit()
    return {"status": "success", "detail": "Client deleted"}
